#!/usr/bin/env python3
"""Generate SVG graphics with various templates."""

import argparse
import json
import sys
from pathlib import Path


def generate_icon(output, data):
    """Generate a simple icon SVG."""
    icon_data = json.loads(data) if isinstance(data, str) else data
    shape = icon_data.get("shape", "circle")
    color = icon_data.get("color", "#4a90d9")
    size = icon_data.get("size", 100)
    
    shapes = {
        "circle": f'<circle cx="{size//2}" cy="{size//2}" r="{size//2-5}" fill="{color}"/>',
        "square": f'<rect x="5" y="5" width="{size-10}" height="{size-10}" rx="10" fill="{color}"/>',
        "star": f'<polygon points="{size//2},5 {size//4+5},{size//4} {size-5},{size//4} {size//2},{size//2} {size//4+5},{size*3//4} {size-5},{size*3//4}" fill="{color}"/>',
        "heart": f'<path d="M{size//2},{size*3//4} C{size//4},{size//2} 5,{size//3} {size//2},{size//6} C{size-5},{size//3} {size*3//4},{size//2} {size//2},{size*3//4}" fill="{color}"/>',
    }
    
    svg = f'''<?xml version="1.0" encoding="UTF-8"?>
<svg width="{size}" height="{size}" xmlns="http://www.w3.org/2000/svg">
  {shapes.get(shape, shapes["circle"])}
</svg>'''
    
    Path(output).write_text(svg)
    print(f"✅ Icon saved to: {output}")


def generate_diagram(output, data):
    """Generate a flowchart/diagram SVG."""
    diagram_data = json.loads(data) if isinstance(data, str) else data
    title = diagram_data.get("title", "Diagram")
    boxes = diagram_data.get("boxes", [])
    
    width = diagram_data.get("width", 600)
    height = max(400, len(boxes) * 80 + 100)
    
    svg_boxes = ""
    y = 80
    for i, box in enumerate(boxes):
        text = box.get("text", f"Step {i+1}")
        color = box.get("color", "#4a90d9")
        x = width // 2 - 75
        svg_boxes += f'''
  <rect x="{x}" y="{y}" width="150" height="50" rx="8" fill="{color}" stroke="#333" stroke-width="2"/>
  <text x="{x+75}" y="{y+30}" text-anchor="middle" fill="white" font-size="14" font-weight="bold">{text}</text>'''
        if i < len(boxes) - 1:
            svg_boxes += f'''
  <line x1="{x+75}" y1="{y+50}" x2="{x+75}" y2="{y+70}" stroke="#333" stroke-width="2" marker-end="url(#arrow)"/>'''
        y += 80
    
    svg = f'''<?xml version="1.0" encoding="UTF-8"?>
<svg width="{width}" height="{height}" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <marker id="arrow" markerWidth="10" markerHeight="10" refX="9" refY="3" orient="auto">
      <path d="M0,0 L0,6 L9,3 z" fill="#333"/>
    </marker>
  </defs>
  <rect width="{width}" height="{height}" fill="#f8f9fa" rx="15"/>
  <text x="{width//2}" y="40" text-anchor="middle" font-size="20" font-weight="bold" fill="#333">{title}</text>
  {svg_boxes}
</svg>'''
    
    Path(output).write_text(svg)
    print(f"✅ Diagram saved to: {output}")


def generate_portrait(output, data):
    """Generate a fun portrait/avatar SVG."""
    portrait_data = json.loads(data) if isinstance(data, str) else data
    name = portrait_data.get("name", "Character")
    style = portrait_data.get("style", "friendly")
    
    colors = {
        "friendly": {"bg": "#1a1a2e", "face": "#ff6b6b", "accent": "#ffd700"},
        "robot": {"bg": "#2d3436", "face": "#636e72", "accent": "#00cec9"},
        "nature": {"bg": "#00b894", "face": "#fdcb6e", "accent": "#e17055"},
    }
    c = colors.get(style, colors["friendly"])
    
    svg = f'''<?xml version="1.0" encoding="UTF-8"?>
<svg width="300" height="350" xmlns="http://www.w3.org/2000/svg">
  <rect width="300" height="350" fill="{c['bg']}" rx="20"/>
  <text x="150" y="40" text-anchor="middle" fill="{c['accent']}" font-size="20" font-weight="bold">{name}</text>
  <ellipse cx="150" cy="150" rx="80" ry="90" fill="{c['face']}" stroke="{c['accent']}" stroke-width="3"/>
  <circle cx="120" cy="130" r="15" fill="white"/>
  <circle cx="180" cy="130" r="15" fill="white"/>
  <circle cx="120" cy="130" r="8" fill="{c['bg']}"/>
  <circle cx="180" cy="130" r="8" fill="{c['bg']}"/>
  <circle cx="122" cy="128" r="3" fill="white"/>
  <circle cx="182" cy="128" r="3" fill="white"/>
  <path d="M 120 170 Q 150 200 180 170" stroke="{c['bg']}" stroke-width="4" fill="none"/>
  <text x="150" y="280" text-anchor="middle" fill="white" font-size="14">Generated by OpenClaw</text>
  <text x="150" y="300" text-anchor="middle" fill="{c['accent']}" font-size="12">🎨 Image Generator Skill</text>
</svg>'''
    
    Path(output).write_text(svg)
    print(f"✅ Portrait saved to: {output}")


def generate_chart_svg(output, data):
    """Generate a simple bar chart in SVG."""
    chart_data = json.loads(data) if isinstance(data, str) else data
    title = chart_data.get("title", "Chart")
    values = chart_data.get("values", [30, 70, 50, 90, 40])
    labels = chart_data.get("labels", ["A", "B", "C", "D", "E"])
    colors = chart_data.get("colors", ["#4a90d9", "#ff6b6b", "#ffd700", "#00cec9", "#a29bfe"])
    
    width = chart_data.get("width", 500)
    height = 300
    bar_width = 50
    gap = (width - len(values) * bar_width) // (len(values) + 1)
    max_val = max(values) if values else 1
    
    bars = ""
    for i, (val, label) in enumerate(zip(values, labels)):
        x = gap + i * (bar_width + gap)
        bar_height = int((val / max_val) * 200)
        y = 250 - bar_height
        color = colors[i % len(colors)]
        bars += f'''
  <rect x="{x}" y="{y}" width="{bar_width}" height="{bar_height}" fill="{color}" rx="5"/>
  <text x="{x + bar_width//2}" y="270" text-anchor="middle" font-size="12" fill="#333">{label}</text>
  <text x="{x + bar_width//2}" y="{y - 5}" text-anchor="middle" font-size="11" fill="#333">{val}</text>'''
    
    svg = f'''<?xml version="1.0" encoding="UTF-8"?>
<svg width="{width}" height="{height}" xmlns="http://www.w3.org/2000/svg">
  <rect width="{width}" height="{height}" fill="#f8f9fa" rx="15"/>
  <text x="{width//2}" y="30" text-anchor="middle" font-size="18" font-weight="bold" fill="#333">{title}</text>
  <line x1="30" y1="250" x2="{width-20}" y2="250" stroke="#999" stroke-width="2"/>
  {bars}
</svg>'''
    
    Path(output).write_text(svg)
    print(f"✅ Chart saved to: {output}")


def main():
    parser = argparse.ArgumentParser(description="Generate SVG graphics")
    parser.add_argument("--output", "-o", required=True, help="Output SVG file path")
    parser.add_argument("--template", "-t", required=True, 
                       choices=["icon", "diagram", "portrait", "chart"],
                       help="Template to use")
    parser.add_argument("--data", "-d", default="{}", help="JSON data for customization")
    
    args = parser.parse_args()
    
    generators = {
        "icon": generate_icon,
        "diagram": generate_diagram,
        "portrait": generate_portrait,
        "chart": generate_chart_svg,
    }
    
    generator = generators.get(args.template)
    if generator:
        generator(args.output, args.data)
    else:
        print(f"❌ Unknown template: {args.template}")
        sys.exit(1)


if __name__ == "__main__":
    main()
